---
- name: Prepare basic env for php apps on all nodes
  hosts: localhost
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - tools
    - php
    - nginx
    - composer
    - mysql
    - magento2