---
- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: Add php repository PHP 5.6
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present

- name: Update apt
  apt: update_cache=yes

- name: Install PHP
  apt: name=php5 state=latest force=yes

- name: Intsall PHP packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - php5-cli
    - php5-gd
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-dev
    - php5-fpm
    - php5-curl
    - php-soap